apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  SEED_USERNAME: ZGVtbw==
  SEED_USER_PASSWORD: ZGVtbw==
stringData:
  AMQP_EXCHANGE: "test"
  AMQP_USER: "demo"
  AMQP_PASSWORD: "demo"
  AMQP_HOSTNAME : "rmq-clusterip"